[package]
name = "lbm_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray-npy = "0.8.1"
ndarray = "0.15.6"
ndarray-parallel = "0.1"
chrono = "0.4.23"
dotenv = "0.15.0"
rayon = "1.5"
